//! Rust type bindings for the Model Context Protocol (MCP) specification.
//!
//! This crate provides strongly-typed Rust structs and enums that represent the MCP protocol,
//! automatically generated from the protocol's JSON schema specification in `spec/` using the
//! `typify` crate.
//!
//! The Model Context Protocol is a JSON-RPC based protocol that enables communication between
//! LLM clients and servers, allowing them to:
//! - Exchange messages and prompts
//! - Access and monitor resources
//! - Call tools and functions
//! - Handle capabilities negotiation
//! - Manage logging and notifications

#![allow(irrefutable_let_patterns)]

/// The latest MCP protocol version supported by this crate.
pub const LATEST_PROTOCOL_VERSION: &str = "2024-11-05";

/// The list of MCP protocol versions supported by this crate.
pub const SUPPORTED_PROTOCOL_VERSIONS: &[&str] = &[LATEST_PROTOCOL_VERSION];

/// Type bindings of the MCP JSON Schema generated by the `typify` crate.
#[cfg(feature = "2024_11_05")]
pub mod v2024_11_05;
